- type: job
  id: Contractor
  name: job-name-contractor
  description: job-description-contractor
  playTimeTracker: JobContractor
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4000
    - !type:WealthRequirement
      below: 25001
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess


- type: entity
  parent: IDCardStandard
  id: SpacerIDCard
  name: Spacer ID card
  components:
  - type: Sprite
    layers:
    - state: default
    - state: idpassenger
  - type: PresetIdCard
    job: Spacer

- type: startingGear
  id: ContractorGear
  equipment:
    ears: ClothingHeadsetGrey
    id: SpacerIDCard
