- type: job
  id: Spacer
  name: job-name-spacer
  description: job-description-spacer
  playTimeTracker: JobSpacer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 500
  startingGear: ContractorGear
  icon: "JobIconPassenger"
  supervisors: job-supervisors-hire
  accessGroups:
  - GeneralAccess
