- type: job
  id: AdjutantDSM
  name: job-name-adjutant
  description: job-description-adjutant
  playTimeTracker: JobAdjutantDSM
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
    - !type:FactionRequirement
      factionID: "DSM"
  weight: 55
  startingGear: AdjutantGear
  alwaysUseSpawner: true
  icon: "JobIconImperialAdjutant"
  requireAdminNotify: true
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-adjutant
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - DSMFunds
  - Maintenance
  - EmpireNoble
  - EmpireAdjutant
  - EmpireSoldier
  - Service
  - Empire
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - DSMFunds
  - ScribesGuild
  - LogisticsWealth

- type: startingGear
  id: AdjutantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitImperialAdjutantFormal
    back: ClothingBackpackSatchelLeatherFilledDSM
    shoes: ClothingShoesBootsImperialLongboots
    head: ClothingHeadHatImperialBeret
    outerClothing: ClothingOuterCoatImperialAdjutant
    id: AdjutantPDA
    pocket1: ImperialPassportBareLegit
    belt: WeaponRevolverSnubnose
    ears: ClothingHeadsetEmpire
    gloves: ClothingHandsGlovesImperialAdjutantGloves
