- type: job
  id: KnightDSM
  name: job-name-knight
  description: job-description-knight
  playTimeTracker: JobKnightDSM
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 35000
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
    - !type:SexRequirement
      allowed:
        - Male
    - !type:FactionRequirement
      factionID: "DSM"
  weight: 22
  startingGear: KnightGear
  alwaysUseSpawner: true
  icon: "JobIconImperialKnight"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-knight
  access:
  - Command
  - Empire
  - Maintenance
  - Service
  - ScribesGuild
  - LogisticsWealth
  - EmpireNoble
  - EmpireSoldier
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: KnightGear
  equipment:
    id: KnightPDA
    ears: ClothingHeadsetEmpire
    jumpsuit: ClothingUniformJumpsuitImperialCombat
    shoes: ClothingShoesBootsImperialJackboots
    head: ClothingHeadHelmetImperialKnightCommanderHelmet
    outerClothing: ClothingOuterArmorImperialArmorPrestige
    gloves: ClothingHandsGlovesImperialLonggloves
    pocket1: ImperialPassportBareLegit
