- type: job
  id: SoldatATH
  name: job-name-soldat
  description: job-description-soldat
  playTimeTracker: JobSoldatATH
  requirements:
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
        - Reptilian
        - Oni
    - !type:FactionRequirement
      factionID: "ATH"
  weight: 84
  startingGear: SoldatGear
  alwaysUseSpawner: true
  icon: "JobIconSoldat"
  requireAdminNotify: true
  supervisors: job-supervisors-ath
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-soldatATH
  access:
  - EmergencyShuttleRepealAll
  - Captain
  - HeadOfPersonnel
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfSecurity
  - ResearchDirector
  - Frontier # Frontier
  - Cryogenics
  - Security
  - Detective
  - Armory
  - Brig
  - Lawyer
  - Engineering
  - Mail # Frontier
  - Medical
  - Quartermaster
  - Salvage
  - Cargo
  - Research
  - StationTrafficController # Frontier
  - Maintenance
  - External
  - Theatre
  - Bar
  - Chemistry
  - Kitchen
  - Chapel
  - Hydroponics
  - Atmospherics
  - Command
  - Maintenance
  - Service
  - External
  - Authority

- type: startingGear
  id: SoldatGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAuthoritySoldat
    shoes: ClothingShoesBootsJack
    head: ClothingHeadHatAuthoritySoldat
    belt: ClothingBeltAuthorityPouches
    gloves: ClothingHandsGlovesFingerless
    id: SoldatPDA
    ears: ClothingHeadsetAuthority
