- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: 5
  roles:
  - Borg
  - GliessianDockmaster
  - GliessianSheriff
  - Spacer
 # - Botanist
 # - Boxer
 # - Chaplain
 # - Chef
 # - Clown
#  - HeadOfPersonnel
 # - Lawyer
 # - Librarian
 # - Mime
 # - Musician
  - Contractor
 # - Reporter
 # - Visitor
 # - Zookeeper
 # - ServiceWorker
  enabled: true

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - KommissarNCWL
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  primary: false
  weight: 100
  enabled: false

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: -93
  primary: false

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - Detective
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Warden
  enabled: false

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  weight: -92
  primary: false

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false
- type: department
  id: NCWL
  description: department-NCWL-description
  color: "#FFD580"
  weight: 100
  roles:
  - AdministratorNCWL
  - KommissarNCWL
  - SanitarNCWL
  - ArtificerNCWL
  - DoktorNCWL
  - KapitanNCWL
  - KadetNCWL
  enabled: true

- type: department
  id: NCSP
  description: department-NCSP-description
  color: "#DC143C"
  weight: 90
  roles:
  - RingleaderNCSP
  - LieutenantNCSP
  - InfanteerNCSP
  - TechnicianNCSP
  - RipperdocNCSP
  - ChemcookNCSP
  - OperativeNCSP
  - IntelligenceOfficerNCSP
  - CyberdawnTechNCSP
  - ForemanNCSP
  - ShipbreakerNCSP
  enabled: true

- type: department
  id: DSM
  description: department-DSM-description
  color: "#684871"
  weight: 85
  roles:
  - FreeholderDSM
  - LevymanDSM
  - KnightDSM
  - WealthDSM
  - ForemanDSM
  - ScribeDSM
  - TemplarDSM
  - SurgeonDSM
  - CourtierDSM
  - AdjutantDSM
  - GovernorDSM
  - AdvocatusDSM
  - ArchmaesterDSM
  enabled: true

- type: department
  id: SRM
  description: department-SRM-description
  color: "#4a6741"
  weight: 80
  roles:
  - TenderSRM
  - AcolyteSRM
  - HunterSRM
  - MontagneSRM
  - OverseerSRM
  enabled: false

- type: department
  id: SHI
  description: department-SHI-description
  color: "#4a6741"
  weight: 75
  roles:
  - ExecutiveSHI
  - BoardSHI
  - HighsecSHI
  - CorpsecSHI
  - EmployeeSHI
  - MedtechSHI
  enabled: false

- type: department
  id: CMM
  description: department-CMM-description
  color: "#5191e0"
  weight: 70
  roles:
  - OrdnancemanCMM
  - MachinistCMM
  - PhysicianCMM
  - MinutemanCMM
  - WatchmasterCMM
  - DeputyMarshalCMM
  - MarshalCMM
  enabled: true

- type: department
  id: TAP
  description: department-TAP-description
  color: "#50c878"
  weight: 55
  roles:
  - ProphetTAP
  - AcolyteTAP
  - TinkererTAP
  - TechminerTAP
  - HangarTechTAP
  - Antiquarian
  - BeltrunnerTAP
  - DraugrTAP
  - ServileTAP
  enabled: true

- type: department
  id: ATH
  description: department-ATH-description
  color: "#ffffed"
  weight: 40
  roles:
  - KommandantATH
  - LeutnantATH
  - KanoneerATH
  - SoldatATH
  - SanitatATH
  enabled: true
