- type: job
  id: ChemcookNCSP
  name: job-name-chemcook
  description: job-description-chemcook
  playTimeTracker: JobChemcookNCSP
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 8000
    - !type:FactionRequirement
      factionID: "TFSC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-syndoc
  weight: 16
  startingGear: ChemcookGear
  alwaysUseSpawner: true
  icon: "JobIconSyndieChemcook"
  requireAdminNotify: false
  supervisors: You answer to the interests of the Interdyne Pharmaceuticals Company. Whichever you decide with your colleagues they be.
  canBeAntag: false
  access:
  - Command
  - Maintenance
  - SyndicateBasic
  - SyndicateInterdyne
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: ChemcookGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSyndicateInterdyne
    gloves: ClothingHandsGlovesFingerless
    mask: ClothingMaskSyndicateFacemask
    shoes: ClothingShoesBootsCombat
    outerClothing: ClothingOuterArmorSyndicateArmorvestInterdyne
    belt: ClothingBeltSyndicateWebbingInterdyne
    head: ClothingHeadHelmetSyndicateBasicInterdyne
    id: ChemcookPDA
    ears: ClothingHeadsetNCSPInterdyne
