- type: job
  id: Antiquarian
  name: job-name-antiquarian
  description: job-description-antiquarian
  playTimeTracker: JobAntiquarian
  requirements:
    - !type:FactionRequirement
      factionID: "TAP"
    - !type:SpeciesRequirement
      allowedOnly:
        - Human
  weight: 1
  startingGear: AntiquarianGear
  alwaysUseSpawner: true
  icon: "JobIconAntiquarian"
  requireAdminNotify: false
  supervisors: job-supervisors-tap
  canBeAntag: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: ChatRank
        rank: crescent-rank-antiquarian
  - !type:AddComponentSpecial
    components:
      - type: Telepathic
  access:
  - Families
  - Izdari
  - Command
  - Maintenance
  - Antiquarian
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: AntiquarianGear
  equipment:
    id: AntiquarianPDA
    ears: ClothingHeadsetFamilies
    shoes: ClothingShoesBootsCombat
    gloves: ClothingHandsGlovesFingerless
    jumpsuit: ClothingUniformJumpsuitAntiquarianFamilies
    back: BackpackAntiquarianSatchelFilled
